version: '3'

services:
  pythonservice:
    environment:
      PYTHONDONTWRITEBYTECODE: ${PYTHONDONTWRITEBYTECODE}
      LINK: ${LINK}
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
        - "./tests:/tests"